Global:
  infer_imgs: "F:/face_paddle_datasets_1000/images/00000688.jpg"
  rec_inference_model_dir: "H:/PycharmProjects/Github/paddle/PaddleFace/inference"
  batch_size: 1
  use_gpu: False
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: [112, 112]
        return_numpy: False
        interpolation: bilinear
        backend: cv2
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: hwc
    - ToCHWImage:

RecPostProcess: null


#indexing engine config
#IndexProcess:
#  index_method: "HNSW32" # supported: HNSW32, IVF, Flat
#  index_dir: "./recognition_demo_data_v1.1/gallery_product/index"
#  image_root: "F:/face_paddle_datasets_1000"
#  data_file:  "F:/face_paddle_datasets_1000/label.txt"
#  index_operation: "new" # suported: "append", "remove", "new"
#  delimiter: " "
#  dist_type: "IP"
#  embedding_size: 512
#  batch_size: 32

IndexProcess:
  index_dir: "./recognition_demo_data_v1.1/gallery_product/index"
  dist_type: "IP"
  return_k: 5
  score_thres: 0.5
  hamming_radius: 100